### ISSUE TITLE
Sprachwechsler

### ISSUE THREAD

**Issue by vergissberlin** [NULLzuEINS/bbw-leben-mit-avws#1]
**Es muss zwischen drei Sprachen gewechselt werden können:**

- Normale Sprache
- Einfache Sprache
- Gebärdensprache

## Anforderungen
- Die drei Sprachenbuttons enthalten aus eine Grafik
- Die Buttons sind etwas doppelt so groß wie die horizontale Menü-Leiste
- Ist eine Sprache gewählt, ist der entsprechende Button deutlich hervorgehoben, so dass die Besucher erkennen können, welche Sprache aktiviert wurde.

Mit einem Klick auf einen der Sprachbuttons Button, bleibt man auf der aktuellen Seite insofern eine Übersetzung vorhanden ist.

**Comment by vergissberlin** [comment]
Der Sprachwechsel soll über der Haupnavigation positioniert werden. (Desktop und Mobil)
Als Vorbild zu Gestaltung dient hier https://www.philippus-leipzig.de/

**Comment by ozetsche** [comment]
Wichtige Änderung zum Sprachenswitch:
Wir benötigen nun doch bitte nur zwei Sprachen:
1) Text / (ohne Bezeichner)
2) Deutsche Gebärdensprache /dgs/

Die Icons dafür sind in Bearbeitung.

**Comment by vergissberlin** [comment]
@ozetsche An der Gestaltung der Sprachnavigation ändert dies jedoch nichts oder?

**Comment by ozetsche** [comment]
@vergissberlin Also sofern Sie damit die Position meinen, ändert sich nichts daran. Sie soll weiterhin über dem Menü stehen, besteht aber entsprechend nur aus den beiden Buttons "Text" und "Deutsche Gebärdensprache". Nur zwischen diesen beiden Sprachen muss man switchen können.

**Comment by vergissberlin** [comment]
@ozetsche Bitte schicken Sie mir noch bei icons zu.

**Comment by ozetsche** [comment]
@vergissberlin  Die Icons habe ich Ihnen heute gegen 19 Uhr per Mail zugesendet.
Brauchen Sie vielleicht das DGS Icon in einer anderen Farbe?

**Comment by vergissberlin** [comment]
@ozetsche Die Icons sind zwar im SVG Format, enthalten aber base64 codierte  Grafiken. Eigentlich sollten darin die Pfade enthalten sein. Dadurch gehen folgende Vorteile verloren:
- Geringerer Speicherbedarf
- Skalierbarkeit
- Hohe Auflösung
- Manipulierbarkeit der Farben durch CSS (z.B. beim Hover)


## Beispiel

**So sehen die Icons derzeit aus**
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="496px" height="496px" viewBox="0 0 496 496" enable-background="new 0 0 496 496" xml:space="preserve">  <image id="image0" width="496" height="496" x="0" y="0"
    xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfAAAAHwCAQAAADzpfVtAAAAAXNSR0IArs4c6QAAAAJiS0dEAP+H
j8y/AAAACXBIWXMAAC4jAAAuIwF4pT92AAAO8klEQVR42u3de4yl5UHH8eecmTk7O7sLCyy3XS6
QAFluyxQWqASqVDbKn80KlUTmiYkeImXJiWKprEkNq3WKklJNZoaNaUJVmwbq6aahrYWIW1psZTLslfY6+zOfeaMf2qVnGMkNCRDA4MoSWBcYAAAAASUVORK5CYII=" />
</svg>
```

**So sollten sie in etwas aussehen:**
```
<svg version="1.2" baseProfile="tiny"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
	 x="0px" y="0px" width="1600px" height="400px" viewBox="0 0 1600 400" overflow="visible" xml:space="preserve">
<rect width="400" height="400"/>
<path fill="#FFFFFF" d="M154.593,83.608h90.239v24.141h-57.765v77.02h46.844v22.991h-46.844v85.354h58.339v23.278h-90.813V83.608z"
	/>
</svg>
```

**Comment by ozetsche** [comment]
@vergissberlin  Okay. Ich habe die Dateien so von unserem Mediendesigner zugesendet bekommen.
Können Sie mir bitte schreiben, was ich ihm genau sagen soll, was wir brauchen? Ich hatte ihn lediglich gebeten, uns die Icons in einer svg Datei zuzusenden.

**Comment by vergissberlin** [comment]
@ozetsche "Die SVG-Dateien sollen nur Pfade enthalten und keine Bitmap-Grafiken oder Text enthalten." So würde ich es einem Grafiker beschreiben.

Hier ein Extrem-Beispiel wie sich die Qualität verschlechtert wenn das Bild vergrößert wird:
https://monosnap.com/file/ZTJ5PrnNn6OGOmwiw4Yvw0E9d5Y6Pq

Folgendes Bild hingegen lässt sich beliebig vergrößern:
https://www.lwv-hessen.de/fileadmin/template/bootstrap/images/icon_gebaerdensprache_blau.svg

**Comment by ozetsche** [comment]
okay, danke, das werde ich so weitergeben.

André Lademann <notifications@github.com> schrieb am Mi., 13. Juni 2018,
22:44:

**Comment by vergissberlin** [comment]
@ozetsche  Hier werden auch passende Vektorgrafiken zum Kauf angeboten:
http://www.vektorgrafiken24.com/Vektorgrafiken-Shop/Piktogramme/Behinderungen:::16_35:6.html?show=list

**Comment by ozetsche** [comment]
Ah, spannend. Danke für den Hinweis.
Ich gehe davon aus, dass unser Mediendesigner im Laufe des Tages antwortet.

**Comment by ozetsche** [comment]
@vergissberlin Ich habe Ihnen gerade per Mail die beiden Icons und die Wünsche zwecks der Inhaltselemente zugesendet. Vielen Dank!

**Comment by ozetsche** [comment]
@vergissberlin Noch ein Nachtrag zum Hauptmenu, da dieses Issue schon geschlossen ist: Bitte ändern sie noch die Farbhinterlegung im Submenu auf lila. Ich habe von den Kolleginnen die Rückmeldung bekommen, dass wir gerne ein einheitliches Farbkonzept hätten; also Hauptmenu und Submenu lila, sofern es anklickt ist. Vielen Dank!

**Comment by ozetsche** [comment]
@vergissberlin Die Icons zum Sprachenswitch fügen Sie noch ein, oder?

**Comment by vergissberlin** [comment]
@ozetsche Ja, heute Abend.

**Comment by vergissberlin** [comment]
@ozetsche Ich habe die Icons vektorisiert und eingebaut.
*Bereit zu Abnahme*
