### ISSUE TITLE
Sprechende URLs

### ISSUE THREAD

**Issue by ozetsche** [NULLzuEINS/bbw-leben-mit-avws#10]
Bitte die URLs entsprechend ändern.

**Comment by vergissberlin** [comment]
**Die unterschiedlichen Sprachen sollen in der URL wie folgt erscheinen:**
- Text `/` (ohne Bezeichner)
- Deutsche Gebärdensprache `/dgs/`
- Einfache Sprache `/einfach /`

**Comment by vergissberlin** [comment]
✅ Umgesetzt:
- https://leben-mit-avws.de/methode-der-datenerhebung/beispielseite/
- https://leben-mit-avws.de/dgs/methode-der-datenerhebung/beispielseite/
@ozetsche Bereit zur Abnahme
