### ISSUE TITLE
Theme-Erstellung

### ISSUE THREAD

**Issue by vergissberlin** [NULLzuEINS/bbw-leben-mit-avws#5]
- Logos und Farbcodes werden vom Auftraggeber bereitsgestellt.
- Das Logo und die Farben werden in Abstimmung mit dem Auftraggeber im Theme angewandt.

**Comment by vergissberlin** [comment]
@ozetsche Wir hatten heute besprochen, dass die Toolbar von schwarz, in BBW-Blau eingefärbt  werden soll. Bei der Entwicklung hatte ich sie zufällig in BBW-Lila getaucht und war überrascht wie viel ruhiger das Erscheinungsbild dadurch ist.
https://leben-mit-avws.de/de/methode-der-datenerhebung/beispielseite/

Was meinen Sie?

**Comment by ozetsche** [comment]
@vergissberlin Ja, das sieht auch nicht schlecht aus. Ich habe davon mal einen Screenshot gemacht.
Könnten Sie bitte einen Screenshot von der Seite mit BBW-blauer Toolbar machen? Dann hätte man einen Vergleich, der mir gerade fehlt.

**Comment by vergissberlin** [comment]
@ozetsche Hier der Vergleich. Ich habe auch die Unternavigation entsprechend eingefärbt:

https://monosnap.com/file/9jm5WJRdCiprkYIACZzmeWgepAIACZ
https://monosnap.com/file/yZ3MI8ego8hNxJdhMsjKI5xleh0Tws

**Comment by ozetsche** [comment]
Vielen Dank, habe es zum Feedback an die Kolleginnen weitergegeben. Mir
persönlich würde lila auch besser gefallen.

André Lademann <notifications@github.com> schrieb am Mi., 13. Juni 2018,
22:53:

**Comment by ozetsche** [comment]
@vergissberlin  Nach dem Feedback der Kolleginnen würden wir doch lieber beim zweiten, also beim alten Design mit dem blau bleiben.
Ich habe Ihnen eben auch noch eine Mail mit einem Bild geschickt, auf dem Sie sehen müssten, dass sich die Menüleiste verschoben hat. Könnten Sie das bitte noch reparieren? Danke!

**Comment by vergissberlin** [comment]
@ozetsche Wie besprochen ist die Toolbar nun genau wie die Unternavigation in blau.

*Bereit zur Abnahme*

**Comment by ozetsche** [comment]
@vergissberlin Ich dachte, wir sind bei einer einheitlichen Farbe für die beiden Menus verblieben, oder nicht? Also sofern das Kopfmenu in lila ist, ist auch das Untermenu in lila? Ich habe gerade noch einmal zur Sicherheit eine Nachricht an die Kolleginnen geschrieben und hoffe, sie antworten bis morgen Mittag.
