### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by vergissberlin** [NULLzuEINS/bbw-leben-mit-avws#6]
**User story**
Als Redakteur möchte ich den Inhalt der Seite pflegen können. Dies beinhaltet die Seiteninhalte und die Seitenstruktur. Diese können hinzugefügt, gelöscht und bearbeitet werden.
 
**Akzeptanzkriterien**
- Seiten
-- Seiteneigenschaften können bearbeitet
-- Seiten können neu angelegt, verschoben, gelöscht und bearbetet werden
- Seiteninhalte
-- Seiten können neu angelegt, verschoben, gelöscht und bearbetet werden
- Die eigenen Benutzereinstellungen können bearbeitet werden
- Dateien hochladen und Verzeicnisse anlegen

#### Seiten und seiteninhalte
1. Loggen Sie sich als Redakteur ein
- Legen Sie eine neue Seite an
- Bearbeiten Sie die Seiteninhalte
- Legen Sie ein neues Inhaltselement an (z.B. Bild-Text)
- Bearbeiten sie den Inhalt
- Schauen Sie sich das Ergebnis im *Frontend* an

#### Dateiverwaltung
1. Rufen sie im Backend den Menüpunkt *Files*/*Dateien* auf.
- Legen Sie ein Verzeichnis an
- Laden Sie eine Datei hoch

#### Benutzereinstellungen
1. Verändern Sie in den Benutzereinstellungen ihren Vornamen und drück sie auf Speichern
- Prüfen Sie ob der neue Name im Backend angezeigt wird.

**Zusätzlicher Kontext**
TYPO3 bietet ein granulares Rechtesystem an. Die Rechte können für Gruppen und einzelne Benutzer definiert werden.

**Comment by vergissberlin** [comment]
@ozetsche Fertig zur Abnahme

**Comment by vergissberlin** [comment]
@ozetsche Bitte ergänzen sie noch die Namen, Vornamen und Nutzernamen der zwei weiteren Redakteure. Besten Dank!

**Comment by ozetsche** [comment]
@vergissberlin Namen der beiden weiteren Redakteure:
Lissy Rinneberg-Schmidt --> Benutzername Lissy
Stephanie Meiland ---> Stephanie
Meinten Sie das so?

**Comment by vergissberlin** [comment]
@ozetsche Ich habe die beiden Benutzer angelegt.

*Bereit zur Abnahme*
