### ISSUE TITLE
Videoplayer Aktion Mensch

### ISSUE THREAD

**Issue by vergissberlin** [NULLzuEINS/bbw-leben-mit-avws#8]
## User story

Als Redakteur habe ich die Möglichkeit Videos einzubinden. Neben der Auswahl von Youtube-Videos habe ich die Möglichkeit, den Videoplayer der Aktion Mensch zur Wiedergabe der Videos zu verwenden.

Die geschieht mit dem TYPO§ CMS Inhaltselement "Plain HTML" indem der entsprechende HTML Code hineinkopiert wird.

## Abgrenzung

Eine Erweiterung des TYPO3-Standard players um eine Auswahlmöglichkeit des Player ist in diesem Projekt nicht enthalten.

**Comment by vergissberlin** [comment]
@ozetsche Bitte Einbindung mit HTML Element Testen

**Comment by vergissberlin** [comment]
@ozetsche Das Inhaltselement HTML steht nun auch Redakteuren zur Auswahl

**Comment by ozetsche** [comment]
Danke.

André Lademann <notifications@github.com> schrieb am Mi., 13. Juni 2018,
22:55:
